const fs = require('fs-extra');
const postcss = require('postcss');
const postcssModules = require('postcss-modules');
const { provider } = require('jimple');
const ConfigurationFile = require('../../abstracts/configurationFile');
/**
 * This service creates a configuration with all the settings for the plugins this build engine
 * uses.
 * @extends {ConfigurationFile}
 */
class RollupPluginSettingsConfiguration extends ConfigurationFile {
  /**
   * @param {Logger}             appLogger          To send to the plugins that support a logger.
   * @param {BabelConfiguration} babelConfiguration To get the target Babel configuration.
   * @param {BabelHelper}        babelHelper        To disable the `modules` setting of the Babel
   *                                                env preset for a target, as Rollup requires.
   * @param {Events}             events             To reduce the settings.
   * @param {Object}             packageInfo        To get the dependencies and define them as
   *                                                externals for Node targets.
   * @param {PathUtils}          pathUtils          Require by `ConfigurationFile` in order to
   *                                                build the path to the overwrite file. It's
   *                                                also used to build the paths of SSL
   *                                                certificates the dev server plugin may use.
   * @param {Object}             rollupPluginInfo   To get the name of the _"sub packages"_ the
   *                                                plugin provides and that should be marked as
   *                                                external.
   * @param {TargetsHTML}        targetsHTML        To get the path to a target HTML template
   *                                                file.
   */
  constructor(
    appLogger,
    babelConfiguration,
    babelHelper,
    events,
    packageInfo,
    pathUtils,
    rollupPluginInfo,
    targetsHTML
  ) {
    super(pathUtils, 'rollup/plugins.config.js');
    /**
     * A local reference for the `appLogger` service.
     * @type {Logger}
     */
    this.appLogger = appLogger;
    /**
     * A local reference for the `babelConfiguration` service.
     * @type {BabelConfiguration}
     */
    this.babelConfiguration = babelConfiguration;
    /**
     * A local reference for the `babelHelper` service.
     * @type {BabelHelper}
     */
    this.babelHelper = babelHelper;
    /**
     * A local reference for the `events` service.
     * @type {Events}
     */
    this.events = events;
    /**
     * The project `package.json` information.
     * @type {Object}
     */
    this.packageInfo = packageInfo;
    /**
     * A local reference for the plugin information.
     * @type {RollupPluginInfo}
     */
    this.rollupPluginInfo = rollupPluginInfo;
    /**
     * A local reference for the `targetsHTML` service.
     * @type {TargetsHTML}
     */
    this.targetsHTML = targetsHTML;
  }
  /**
   * Creates the plugins settings for the required target.
   * This method uses the reducer events `rollup-plugin-settings-configuration-for-node` or
   * `rollup-plugin-settings-configuration-for-browser`, depending on the target type, and then
   * `rollup-plugin-settings-configuration`. The event receives the configuration object, the
   * `params` and it expects an updated configuration object on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @param {Function}                  stats  A function to send to the plugins that support
   *                                           logging stats entries.
   * @return {Object}
   */
  createConfig(params, stats) {
    // Get the external settings.
    const external = this._getExternalSettings(params);
    // Define the basic settings.
    const settings = {
      external,
      globals: this._getGlobalVariablesSettings(params, external.external),
      resolve: this._getResolveSettings(params, stats),
      replace: this._getReplaceSettings(params, stats),
      babel: this._getBabelSettings(params, stats),
      commonjs: this._getCommonJSSettings(params, stats),
      sass: this._getSASSSettings(params, stats),
      css: this._getCSSSettings(params, stats),
      stylesheetAssets: this._getStyleheetAssetsSettings(params, stats),
      stylesheetModulesFixer: this._getStylesheetModulesFixerSettings(params, stats),
      html: this._getHTMLSettings(params, stats),
      json: this._getJSONSettings(params, stats),
      urls: this._getURLsSettings(params, stats),
      watch: this._getWatchSettings(params, stats),
      uglify: this._getUglifySettings(params, stats),
      compression: this._getCompressionSettings(params, stats),
      statsLog: this._getStatsLogSettings(params),
    };

    let eventName;
    // Based on the target type, define the event reducer name and add specific settings.
    if (params.target.is.node) {
      eventName = 'rollup-plugin-settings-configuration-for-node';
      settings.nodeRunner = this._getNodeRunnerSettings(params);
      settings.stylesheetAssetsHelper = this._getStyleheetAssetsHelperSettings(params);
    } else {
      eventName = 'rollup-plugin-settings-configuration-for-browser';
      settings.template = this._getTemplateSettings(params, stats);
      settings.devServer = this._getDevServerSettings(params);
    }
    // Return the reduced settings.
    return this.events.reduce(
      [eventName, 'rollup-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the external dependencies.
   * This method uses the reducer event `rollup-external-plugin-settings-configuration-for-browser`
   * or `rollup-external-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-external-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getExternalSettings(params) {
    const { target, buildType } = params;
    // Define the list of modules that shuld be external.
    const external = [];

    // Push modules the target is excluding by configuration.
    if (target.excludeModules) {
      external.push(...target.excludeModules);
    }
    // If the target is for Node...
    if (target.is.node) {
      // Push the plugin _"sub modules"_.
      external.push(...this.rollupPluginInfo.external.map((dependencyName) => (
        `${this.rollupPluginInfo.name}/${dependencyName}`
      )));
      // Push the production dependencies.
      external.push(...Object.keys(this.packageInfo.dependencies));
      // And if the build is for development, push the dev dependencies too.
      if (buildType === 'development') {
        external.push(...Object.keys(this.packageInfo.devDependencies));
      }
    }
    // Wrap the list on an object.
    const settings = { external };

    const eventName = target.is.node ?
      'rollup-external-plugin-settings-configuration-for-node' :
      'rollup-external-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-external-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the global variables on the bundle. They are actually based on the
   * modules that are handled as external.
   * This method uses the reducer event
   * `rollup-global-variables-plugin-settings-configuration-for-browser` or
   * `rollup-global-variables-plugin-settings-configuration-for-node`, depending on the target
   * type, and then `rollup-global-variables-plugin-settings-configuration`. The event receives
   * the settings, the `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params   A dictionary generated by the top service building
   *                                             the configuration and that includes things like the
   *                                             target information, its entry settings, output
   *                                             paths, etc.
   * @param {Array}                     external The list of modules that will be handled as
   *                                             external dependencies.
   * @return {Object}
   */
  _getGlobalVariablesSettings(params, external) {
    // Define the settings dictionary.
    const settings = {};
    // Loop all the external modules.
    external.forEach((name) => {
      // Format the module name into a variable.
      const globalName = name
      .replace(/\//g, '-')
      .replace(/-(\w)/g, (match, letter) => letter.toUpperCase());
      // Set it on the dictionary using the module name as key.
      settings[name] = globalName;
    });

    const eventName = params.target.is.node ?
      'rollup-global-variables-settings-configuration-for-node' :
      'rollup-global-variables-settings-configuration-for-browser';

    // return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-global-variables-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `resolve` plugin.
   * This method uses the reducer event `rollup-resolve-plugin-settings-configuration-for-browser`
   * or `rollup-resolve-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-resolve-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getResolveSettings(params) {
    const settings = {
      // Add just for basic JS files and JSON.
      extensions: ['.js', '.json', '.jsx'],
    };

    const eventName = params.target.is.node ?
      'rollup-resolve-plugin-settings-configuration-for-node' :
      'rollup-resolve-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-resolve-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `replace` plugin.
   * This method uses the reducer event `rollup-replace-plugin-settings-configuration-for-browser`
   * or `rollup-replace-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-replace-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getReplaceSettings(params) {
    // Add the target definitions as the settings.
    const settings = Object.assign({}, params.definitions);

    const eventName = params.target.is.node ?
      'rollup-replace-plugin-settings-configuration-for-node' :
      'rollup-replace-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-replace-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `babel` plugin.
   * This method uses the reducer event `rollup-babel-plugin-settings-configuration-for-browser`
   * or `rollup-babel-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-babel-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getBabelSettings(params) {
    const { target, targetRules } = params;
    // Get the rule for JS files.
    const jsRule = targetRules.js.getRule();
    // Get the target Babel configuration.
    const baseConfiguration = this.babelConfiguration.getConfigForTarget(target);
    // Disable the `modules` feature for the `env` preset.
    const configuration = this.babelHelper.disableEnvPresetModules(baseConfiguration);
    // Define the plugin settings.
    const settings = Object.assign(
      {},
      configuration,
      {
        // The plugin doesn't support RegExp, so it will use the glob patterns.
        include: [...jsRule.files.glob.include],
        exclude: [...jsRule.files.glob.exclude],
      }
    );

    const eventName = target.is.node ?
      'rollup-babel-plugin-settings-configuration-for-node' :
      'rollup-babel-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-babel-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `commonjs` plugin.
   * This method uses the reducer event `rollup-commonjs-plugin-settings-configuration-for-browser`
   * or `rollup-commonjs-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-commonjs-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getCommonJSSettings(params) {
    /**
     * There are no settings, but because the plugin is used, the method reduces the empty
     * configuration so other plugins/services can update it if needed.
     */
    const settings = {};

    const eventName = params.target.is.node ?
      'rollup-commonjs-plugin-settings-configuration-for-node' :
      'rollup-commonjs-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-commonjs-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `sass` plugin.
   * This method uses the reducer event `rollup-sass-plugin-settings-configuration-for-browser`
   * or `rollup-sass-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-sass-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getSASSSettings(params) {
    const { target, paths, targetRules } = params;
    // Get the rule for SCSS files.
    const scssRule = targetRules.scss.getRule();

    // Define the plugin settings.
    const settings = {
      include: [...scssRule.files.include],
      exclude: [...scssRule.files.exclude],
      options: {
        sourceMapEmbed: true,
        outputStyle: 'compressed',
      },
      processor: this._getStylesProcessor(target.css.modules),
    };

    // If the CSS should be injected, turn on the flag.
    if (target.css.inject) {
      settings.insert = true;
    } else if (target.is.browser) {
      // If the CSS shouldn't be injected and the target is for browser, define a bundle path.
      settings.output = `${target.paths.build}/${paths.css}`;
    } else {
      // Otherwise, it means that is a Node target, so just return the code.
      settings.output = false;
    }

    const eventName = target.is.node ?
      'rollup-sass-plugin-settings-configuration-for-node' :
      'rollup-sass-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-sass-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `css` plugin.
   * This method uses the reducer event `rollup-css-plugin-settings-configuration-for-browser`
   * or `rollup-css-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-css-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @param {Function}                  stats  A function to send to the plugins that support
   *                                           logging stats entries.
   * @return {Object}
   */
  _getCSSSettings(params, stats) {
    const { target, paths, targetRules } = params;
    // Get the rule for SCSS files.
    const cssRule = targetRules.css.getRule();
    // Define the plugin settings.
    const settings = {
      include: [...cssRule.files.include],
      exclude: [...cssRule.files.exclude],
      processor: this._getStylesProcessor(false, { map: true }),
      stats,
    };

    // If the CSS should be injected, turn on the flag.
    if (target.css.inject) {
      settings.insert = true;
    } else if (target.is.browser) {
      // If the CSS shouldn't be injected and the target is for browser, define a bundle path.
      settings.output = `${target.paths.build}/${paths.css}`;
    } else {
      // Otherwise, it means that is a Node target, so just return the code.
      settings.output = false;
    }

    const eventName = target.is.node ?
      'rollup-css-plugin-settings-configuration-for-node' :
      'rollup-css-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-css-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `stylesheetAssets` plugin, which is a projext's plugin that takes
   * care of copying and fixing the paths for the files linked on stylesheets.
   * This method uses the reducer event
   * `rollup-stylesheet-assets-plugin-settings-configuration-for-browser` or
   * `rollup-stylesheet-assets-plugin-settings-configuration-for-node`, depending on the target
   * type, and then `rollup-stylesheet-assets-plugin-settings-configuration`. The event receives
   * the settings, the `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @param {Function}                  stats  A function to send to the plugins that support
   *                                           logging stats entries.
   * @return {Object}
   */
  _getStyleheetAssetsSettings(params, stats) {
    const {
      target,
      paths,
      output,
    } = params;
    // Get the rules for common assets.
    const assetsRules = this._getAssetsRules(params);
    /**
     * Define the file the plugin will parse. If the target injects the CSS or is a Node target,
     * use the main JS file, otherwise, the path for bundling CSS.
     */
    const stylesheet = target.css.inject || target.is.node ?
      output.file :
      `${target.paths.build}/${paths.css}`;

    // Define the plugin settings.
    const settings = {
      stylesheet,
      stats,
      urls: [
        assetsRules.fonts,
        assetsRules.images,
      ],
    };

    const eventName = target.is.node ?
      'rollup-stylesheet-assets-plugin-settings-configuration-for-node' :
      'rollup-stylesheet-assets-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-stylesheet-assets-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `stylesheetModulesFixer` plugin, which is a projext's plugin that
   * parses modules for CSS (stylsheet that Rollup transforms into ES modules) and if they inject
   * the CSS on the browser or they code was moved to a separate bundle, replace their default
   * exports for the named export for CSS Modules locals.
   * This method uses the reducer event
   * `rollup-stylesheet-modules-fixer-plugin-settings-configuration-for-browser` or
   * `rollup-stylesheet-modules-fixer-plugin-settings-configuration-for-node`, depending on the
   * target type, and then `rollup-stylesheet-modules-fixer-plugin-settings-configuration`. The
   * event receives the settings, the `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getStylesheetModulesFixerSettings(params) {
    const { target, targetRules } = params;
    // Get both SCSS and CSS rules.
    const scssRule = targetRules.scss.getRule();
    const cssRule = targetRules.css.getRule();
    // Define the plugin settings.
    const settings = {
      include: [
        ...scssRule.files.include,
        ...cssRule.files.include,
      ],
      exclude: [
        ...scssRule.files.exclude,
        ...cssRule.files.exclude,
      ],
    };

    const eventName = target.is.node ?
      'rollup-stylesheet-modules-fixer-plugin-settings-configuration-for-node' :
      'rollup-stylesheet-modules-fixer-plugin-settings-configuration-for-browser';

    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-stylesheet-modules-fixer-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `stylesheetAssets` helper plugin, which is a projext's plugin
   * that wraps the default exports of stylesheets Rollup transforms into ES modules so
   * the `stylesheetAssets` plugin can find them and parse them.
   * This method uses the reducer event
   * `rollup-stylesheet-assets-helper-plugin-settings-configuration`, it receives the settings,
   * the `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getStyleheetAssetsHelperSettings(params) {
    const { targetRules } = params;
    // Get both SCSS and CSS rules.
    const scssRule = targetRules.scss.getRule();
    const cssRule = targetRules.css.getRule();
    // Define the plugin settings.
    const settings = {
      include: [
        ...scssRule.files.include,
        ...cssRule.files.include,
      ],
      exclude: [
        ...scssRule.files.exclude,
        ...cssRule.files.exclude,
      ],
    };
    // Return the reduced configuration.
    return this.events.reduce(
      'rollup-stylesheet-assets-helper-plugin-settings-configuration',
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `html` plugin.
   * This method uses the reducer event `rollup-html-plugin-settings-configuration-for-browser`
   * or `rollup-html-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-html-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getHTMLSettings(params) {
    /**
     * There are no settings, but because the plugin is used, the method reduces the empty
     * configuration so other plugins/services can update it if needed.
     */
    const settings = {};

    const eventName = params.target.is.node ?
      'rollup-html-plugin-settings-configuration-for-node' :
      'rollup-html-plugin-settings-configuration-for-browser';
    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-html-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `json` plugin.
   * This method uses the reducer event `rollup-json-plugin-settings-configuration-for-browser`
   * or `rollup-json-plugin-settings-configuration-for-node`, depending on the target type, and
   * then `rollup-json-plugin-settings-configuration`. The event receives the settings, the
   * `params` and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @return {Object}
   */
  _getJSONSettings(params) {
    /**
     * There are no settings, but because the plugin is used, the method reduces the empty
     * configuration so other plugins/services can update it if needed.
     */
    const settings = {};

    const eventName = params.target.is.node ?
      'rollup-json-plugin-settings-configuration-for-node' :
      'rollup-json-plugin-settings-configuration-for-browser';
    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-json-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `stylesheetAssets` plugin, which is a projext's plugin that
   * transform files matching a filter by copying its contents into a new file on the output
   * directory and replacing its default export with a URL for them.
   * This method uses the reducer event `rollup-urls-plugin-settings-configuration-for-browser` or
   * `rollup-urls-plugin-settings-configuration-for-node`, depending on the target type, and then
   * `rollup-urls-plugin-settings-configuration`. The event receives the settings, the `params`
   * and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @param {Function}                  stats  A function to send to the plugins that support
   *                                           logging stats entries.
   * @return {Object}
   */
  _getURLsSettings(params, stats) {
    const { target } = params;
    // Get the rules for common assets.
    const assetsRules = this._getAssetsRules(params);
    // Define the plugin settings.
    const settings = {
      urls: [
        assetsRules.fonts,
        assetsRules.images,
        assetsRules.favicon,
      ],
      stats,
    };

    const eventName = target.is.node ?
      'rollup-urls-plugin-settings-configuration-for-node' :
      'rollup-urls-plugin-settings-configuration-for-browser';
    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-urls-plugin-settings-configuration'],
      settings,
      params
    );
  }
  /**
   * Defines the settings for the `template` plugin, which is a projext's plugin that generates
   * and HTML file and injects a list of JS and CSS files.
   * This method uses the reducer event `rollup-html-plugin-settings-configuration-for-browser` or
   * `rollup-html-plugin-settings-configuration-for-node`, depending on the target type, and then
   * `rollup-html-plugin-settings-configuration`. The event receives the settings, the `params`
   * and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @param {Function}                  stats  A function to send to the plugins that support
   *                                           logging stats entries.
   * @return {Object}
   */
  _getTemplateSettings(params, stats) {
    const { target, paths } = params;
    // Get the rules for common assets.
    const assetsRules = this._getAssetsRules(params);
    // Define the plugin settings.
    const settings = {
      template: this.targetsHTML.getFilepath(target),
      output: `${target.paths.build}/${target.html.filename}`,
      stylesheets: target.css.inject ?
        [] :
        [`/${paths.css}`],
      scripts: [`/${paths.js}`],
      urls: [
        assetsRules.images,
        assetsRules.favicon,
      ],
      stats,
    };
    // Return the reduced configuration.
    return this.events.reduce(
      'rollup-template-plugin-settings-configuration',
      settings,
      params
    );
  }
  /**
   * Defines the settings for the Rollup watcher.
   * This method uses the reducer event `rollup-watch-plugin-settings-configuration-for-browser` or
   * `rollup-watch-plugin-settings-configuration-for-node`, depending on the target type, and then
   * `rollup-watch-plugin-settings-configuration`. The event receives the settings, the `params`
   * and expects new settings on return.
   * @param {RollupConfigurationParams} params A dictionary generated by the top service building
   *                                           the configuration and that includes things like the
   *                                           target information, its entry settings, output
   *                                           paths, etc.
   * @param {Function}                  stats  A function to send to the plugins that support
   *                                           logging stats entries.
   * @return {Object}
   */
  _getWatchSettings(params) {
    // Define the plugin settings.
    const settings = {
      clearScreen: false,
    };

    const eventName = params.target.is.node ?
      'rollup-watch-plugin-settings-configuration-for-node' :
      'rollup-watch-plugin-settings-configuration-for-browser';
    // Return the reduced configuration.
    return this.events.reduce(
      [eventName, 'rollup-watch-plugin-settings-configuration'],
      settings,
      params
    );
  }

  _getDevServerSettings(params) {
    const { target } = params;
    const { devServer } = target;
    const settings = {
      host: devServer.host,
      port: devServer.port,
      contentBase: target.paths.build,
      historyApiFallback: !!devServer.historyApiFallback,
      https: null,
      logger: this.appLogger,
    };

    const sslSettings = {};
    let atLeastOneSSLSetting = false;
    [
      'key',
      'cert',
      'ca',
    ].forEach((sslSettingName) => {
      const file = devServer.ssl[sslSettingName];
      if (typeof file === 'string') {
        const filepath = this.pathUtils.join(file);
        if (fs.pathExistsSync(filepath)) {
          atLeastOneSSLSetting = true;
          sslSettings[sslSettingName] = fs.readFileSync(filepath, 'utf-8');
        }
      }
    });

    if (atLeastOneSSLSetting) {
      settings.https = sslSettings;
    }

    return this.events.reduce(
      'rollup-dev-server-plugin-settings-configuration',
      settings,
      params
    );
  }

  _getUglifySettings(params) {
    const settings = {};

    const eventName = params.target.is.node ?
      'rollup-uglify-plugin-settings-configuration-for-node' :
      'rollup-uglify-plugin-settings-configuration-for-browser';

    return this.events.reduce(
      [eventName, 'rollup-uglify-plugin-settings-configuration'],
      settings,
      params
    );
  }

  _getCompressionSettings(params, stats) {
    const { target } = params;
    const rule = this._getARuleForAllTheAssets(params);

    const settings = {
      folder: target.paths.build,
      include: rule.include,
      exclude: rule.exclude,
      stats,
    };

    const eventName = target.is.node ?
      'rollup-compression-plugin-settings-configuration-for-node' :
      'rollup-compression-plugin-settings-configuration-for-browser';

    return this.events.reduce(
      [eventName, 'rollup-compression-plugin-settings-configuration'],
      settings,
      params
    );
  }

  _getStatsLogSettings(params) {
    const { target, paths, buildType } = params;

    const extraEntries = [
      {
        plugin: 'rollup',
        filepath: `${target.paths.build}/${paths.js}`,
      },
    ];

    if (target.sourceMap && target.sourceMap[buildType]) {
      extraEntries.push({
        plugin: 'rollup',
        filepath: `${target.paths.build}/${paths.js}.map`,
      });
    }

    if (target.is.browser && !target.css.inject) {
      extraEntries.push({
        plugin: 'rollup-plugin-sass',
        filepath: `${target.paths.build}/${paths.css}`,
      });
    }

    const settings = {
      extraEntries,
    };

    const eventName = target.is.node ?
      'rollup-stats-plugin-settings-configuration-for-node' :
      'rollup-stats-plugin-settings-configuration-for-browser';

    return this.events.reduce(
      [eventName, 'rollup-stats-plugin-settings-configuration'],
      settings,
      params
    );
  }

  _getNodeRunnerSettings(params) {
    const { output } = params;

    const settings = {
      file: output.file,
      logger: this.appLogger,
    };

    return this.events.reduce(
      'rollup-node-runner-plugin-settings-configuration',
      settings,
      params
    );
  }

  _getAssetsRules(params) {
    const { target, targetRules, paths } = params;
    const commonFontsRule = targetRules.fonts.common.getRule();
    const svgFontsRule = targetRules.fonts.svg.getRule();
    const imagesRule = targetRules.images.getRule();
    const faviconRule = targetRules.favicon.getRule();

    return {
      fonts: {
        include: [
          ...commonFontsRule.files.include,
          ...svgFontsRule.files.include,
        ],
        exclude: [
          ...commonFontsRule.files.exclude,
          ...svgFontsRule.files.exclude,
        ],
        output: `${target.paths.build}/${paths.fonts}`,
        url: `/${paths.fonts}`,
      },
      images: {
        include: [...imagesRule.files.include],
        exclude: [...imagesRule.files.exclude],
        output: `${target.paths.build}/${paths.images}`,
        url: `/${paths.images}`,
      },
      favicon: {
        include: [...faviconRule.files.include],
        exclude: [...faviconRule.files.exclude],
        output: `${target.paths.build}/[name].[ext]`,
        url: '/[name].[ext]',
      },
    };
  }

  _getARuleForAllTheAssets(params) {
    const { target } = params;
    const extensions = [
      'js',
      'jsx',
      'css',
      'html',
      'map',
      'woff',
      'woff2',
      'ttf',
      'eot',
      'jpg',
      'jpeg',
      'png',
      'gif',
      'svg',
      'ico',
    ];
    const extensionsStr = extensions.join('|');
    const extensionsRegex = `\\.(?:${extensionsStr})$`;
    return {
      include: [new RegExp(`${target.paths.build}/.*?${extensionsRegex}`, 'i')],
      exclude: [],
    };
  }

  _getSourceMap(code) {
    const regex = /(\/\*# sourceMappingURL=.*? \*\/)/i;
    const match = regex.exec(code);
    let result;
    if (match) {
      [result] = match;
    }

    return result;
  }

  _getStylesProcessor(modules, processorOptions = {}) {
    const options = Object.assign(
      {},
      {
        map: false,
        from: undefined,
      },
      processorOptions
    );

    return (css, filepath) => {
      let map;
      if (options.map) {
        options.from = filepath;
      } else {
        map = this._getSourceMap(css) || '';
      }

      let locals;
      const plugins = [];
      if (modules) {
        plugins.push(postcssModules({
          getJSON: (filename, json) => {
            locals = json;
          },
        }));
      }

      return postcss(plugins)
      .process(css, options)
      .then((processed) => {
        const cssCode = options.map ?
          `${processed.css}\n` :
          `${processed.css}\n\n${map}\n`;
        let result;
        if (modules) {
          result = {
            css: cssCode,
            locals,
          };
        } else {
          result = cssCode;
        }

        return result;
      });
    };
  }
}

const rollupPluginSettingsConfiguration = provider((app) => {
  app.set('rollupPluginSettingsConfiguration', () => new RollupPluginSettingsConfiguration(
    app.get('appLogger'),
    app.get('babelConfiguration'),
    app.get('babelHelper'),
    app.get('events'),
    app.get('packageInfo'),
    app.get('pathUtils'),
    app.get('rollupPluginInfo'),
    app.get('targetsHTML')
  ));
});

module.exports = {
  RollupPluginSettingsConfiguration,
  rollupPluginSettingsConfiguration,
};
