window.esdocSearchIndex = [
  [
    "projext-plugin-rollup/src/abstracts/configurationfile.js~configurationfile",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html",
    "<span>ConfigurationFile</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/abstracts/configurationFile.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/css/index.js~projextrollupcssplugin",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html",
    "<span>ProjextRollupCSSPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/css/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/compression/index.js~projextrollupcompressionplugin",
    "class/src/plugins/compression/index.js~ProjextRollupCompressionPlugin.html",
    "<span>ProjextRollupCompressionPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/compression/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/devserver/index.js~projextrollupdevserverplugin",
    "class/src/plugins/devServer/index.js~ProjextRollupDevServerPlugin.html",
    "<span>ProjextRollupDevServerPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/devServer/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/noderunner/index.js~projextrollupnoderunnerplugin",
    "class/src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin.html",
    "<span>ProjextRollupNodeRunnerPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/nodeRunner/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/stats/index.js~projextrollupstatsplugin",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html",
    "<span>ProjextRollupStatsPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stats/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html",
    "<span>ProjextRollupStylesheetAssetsHelperPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stylesheetAssets/helper.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/stylesheetassets/index.js~projextrollupstylesheetassetsplugin",
    "class/src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.html",
    "<span>ProjextRollupStylesheetAssetsPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stylesheetAssets/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/stylesheetmodulesfixer/index.js~projextrollupstylesheetmodulesfixerplugin",
    "class/src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin.html",
    "<span>ProjextRollupStylesheetModulesFixerPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stylesheetModulesFixer/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/template/index.js~projextrolluptemplateplugin",
    "class/src/plugins/template/index.js~ProjextRollupTemplatePlugin.html",
    "<span>ProjextRollupTemplatePlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/template/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/urls/index.js~projextrollupurlsplugin",
    "class/src/plugins/urls/index.js~ProjextRollupURLsPlugin.html",
    "<span>ProjextRollupURLsPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/urls/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/utils.js~projextrolluputils",
    "class/src/plugins/utils.js~ProjextRollupUtils.html",
    "<span>ProjextRollupUtils</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/utils.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/windowasglobal/index.js~projextrollupwindowasglobalplugin",
    "class/src/plugins/windowAsGlobal/index.js~ProjextRollupWindowAsGlobalPlugin.html",
    "<span>ProjextRollupWindowAsGlobalPlugin</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/windowAsGlobal/index.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/browserdevelopmentconfiguration.js~rollupbrowserdevelopmentconfiguration",
    "class/src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration.html",
    "<span>RollupBrowserDevelopmentConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/browserDevelopmentConfiguration.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/browserproductionconfiguration.js~rollupbrowserproductionconfiguration",
    "class/src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration.html",
    "<span>RollupBrowserProductionConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/browserProductionConfiguration.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/building/engine.js~rollupbuildengine",
    "class/src/services/building/engine.js~RollupBuildEngine.html",
    "<span>RollupBuildEngine</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/building/engine.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/building/configuration.js~rollupconfiguration",
    "class/src/services/building/configuration.js~RollupConfiguration.html",
    "<span>RollupConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/building/configuration.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/jimpex/frontendfs.js~rollupfrontendfs",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html",
    "<span>RollupFrontendFs</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/jimpex/frontendFs.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/server/middleware.js~rollupmiddleware",
    "class/src/services/server/middleware.js~RollupMiddleware.html",
    "<span>RollupMiddleware</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/server/middleware.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/nodedevelopmentconfiguration.js~rollupnodedevelopmentconfiguration",
    "class/src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration.html",
    "<span>RollupNodeDevelopmentConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/nodeDevelopmentConfiguration.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/nodeproductionconfiguration.js~rollupnodeproductionconfiguration",
    "class/src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration.html",
    "<span>RollupNodeProductionConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/nodeProductionConfiguration.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html",
    "<span>RollupPluginSettingsConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/pluginsConfiguration.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/jimpex/sendfile.js~rollupsendfile",
    "class/src/jimpex/sendFile.js~RollupSendFile.html",
    "<span>RollupSendFile</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/jimpex/sendFile.js</span>",
    "class"
  ],
  [
    "projext-plugin-rollup/src/plugins/compression/index.js~compression",
    "function/index.html#static-function-compression",
    "<span>compression</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/compression/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/css/index.js~css",
    "function/index.html#static-function-css",
    "<span>css</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/css/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/devserver/index.js~devserver",
    "function/index.html#static-function-devServer",
    "<span>devServer</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/devServer/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/noderunner/index.js~noderunner",
    "function/index.html#static-function-nodeRunner",
    "<span>nodeRunner</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/nodeRunner/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/browserdevelopmentconfiguration.js~rollupbrowserdevelopmentconfiguration",
    "variable/index.html#static-variable-rollupBrowserDevelopmentConfiguration",
    "<span>rollupBrowserDevelopmentConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/browserDevelopmentConfiguration.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/browserproductionconfiguration.js~rollupbrowserproductionconfiguration",
    "variable/index.html#static-variable-rollupBrowserProductionConfiguration",
    "<span>rollupBrowserProductionConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/browserProductionConfiguration.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/services/building/engine.js~rollupbuildengine",
    "variable/index.html#static-variable-rollupBuildEngine",
    "<span>rollupBuildEngine</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/building/engine.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/services/building/configuration.js~rollupconfiguration",
    "variable/index.html#static-variable-rollupConfiguration",
    "<span>rollupConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/building/configuration.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/jimpex/frontendfs.js~rollupfrontendfs",
    "function/index.html#static-function-rollupFrontendFs",
    "<span>rollupFrontendFs</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/jimpex/frontendFs.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/services/server/middleware.js~rollupmiddleware",
    "variable/index.html#static-variable-rollupMiddleware",
    "<span>rollupMiddleware</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/server/middleware.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/nodedevelopmentconfiguration.js~rollupnodedevelopmentconfiguration",
    "variable/index.html#static-variable-rollupNodeDevelopmentConfiguration",
    "<span>rollupNodeDevelopmentConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/nodeDevelopmentConfiguration.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/nodeproductionconfiguration.js~rollupnodeproductionconfiguration",
    "variable/index.html#static-variable-rollupNodeProductionConfiguration",
    "<span>rollupNodeProductionConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/nodeProductionConfiguration.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration",
    "variable/index.html#static-variable-rollupPluginSettingsConfiguration",
    "<span>rollupPluginSettingsConfiguration</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/services/configurations/pluginsConfiguration.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/jimpex/sendfile.js~rollupsendfile",
    "variable/index.html#static-variable-rollupSendFile",
    "<span>rollupSendFile</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/jimpex/sendFile.js</span>",
    "variable"
  ],
  [
    "projext-plugin-rollup/src/plugins/stats/index.js~stats",
    "function/index.html#static-function-stats",
    "<span>stats</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stats/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/stylesheetassets/index.js~stylesheetassets",
    "function/index.html#static-function-stylesheetAssets",
    "<span>stylesheetAssets</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stylesheetAssets/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/stylesheetassets/helper.js~stylesheetassetshelper",
    "function/index.html#static-function-stylesheetAssetsHelper",
    "<span>stylesheetAssetsHelper</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stylesheetAssets/helper.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/stylesheetmodulesfixer/index.js~stylesheetmodulesfixer",
    "function/index.html#static-function-stylesheetModulesFixer",
    "<span>stylesheetModulesFixer</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/stylesheetModulesFixer/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/template/index.js~template",
    "function/index.html#static-function-template",
    "<span>template</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/template/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/urls/index.js~urls",
    "function/index.html#static-function-urls",
    "<span>urls</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/urls/index.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/express.js~useexpress",
    "function/index.html#static-function-useExpress",
    "<span>useExpress</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/express.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/jimpex.js~usejimpex",
    "function/index.html#static-function-useJimpex",
    "<span>useJimpex</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/jimpex.js</span>",
    "function"
  ],
  [
    "projext-plugin-rollup/src/plugins/windowasglobal/index.js~windowasglobal",
    "function/index.html#static-function-windowAsGlobal",
    "<span>windowAsGlobal</span> <span class=\"search-result-import-path\">projext-plugin-rollup/src/plugins/windowAsGlobal/index.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/abstracts/configurationfile.js",
    "file/src/abstracts/configurationFile.js.html",
    "src/abstracts/configurationFile.js",
    "file"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#asfactory",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-asFactory",
    "src/abstracts/configurationFile.js~ConfigurationFile#asFactory",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#constructor",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-constructor-constructor",
    "src/abstracts/configurationFile.js~ConfigurationFile#constructor",
    "method"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#createconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-method-createConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#createConfig",
    "method"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#getconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-method-getConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#getConfig",
    "method"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#overwritepaths",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-overwritePaths",
    "src/abstracts/configurationFile.js~ConfigurationFile#overwritePaths",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#parentconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-parentConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#parentConfig",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#pathutils",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-pathUtils",
    "src/abstracts/configurationFile.js~ConfigurationFile#pathUtils",
    "member"
  ],
  [
    "src/express.js",
    "file/src/express.js.html",
    "src/express.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/jimpex.js",
    "file/src/jimpex.js.html",
    "src/jimpex.js",
    "file"
  ],
  [
    "src/jimpex/frontendfs.js",
    "file/src/jimpex/frontendFs.js.html",
    "src/jimpex/frontendFs.js",
    "file"
  ],
  [
    "src/jimpex/frontendfs.js~rollupfrontendfs#constructor",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html#instance-constructor-constructor",
    "src/jimpex/frontendFs.js~RollupFrontendFs#constructor",
    "method"
  ],
  [
    "src/jimpex/frontendfs.js~rollupfrontendfs#delete",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html#instance-method-delete",
    "src/jimpex/frontendFs.js~RollupFrontendFs#delete",
    "method"
  ],
  [
    "src/jimpex/frontendfs.js~rollupfrontendfs#getdirectory",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html#instance-member-getDirectory",
    "src/jimpex/frontendFs.js~RollupFrontendFs#getDirectory",
    "member"
  ],
  [
    "src/jimpex/frontendfs.js~rollupfrontendfs#getfilesystem",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html#instance-member-getFileSystem",
    "src/jimpex/frontendFs.js~RollupFrontendFs#getFileSystem",
    "member"
  ],
  [
    "src/jimpex/frontendfs.js~rollupfrontendfs#read",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html#instance-method-read",
    "src/jimpex/frontendFs.js~RollupFrontendFs#read",
    "method"
  ],
  [
    "src/jimpex/frontendfs.js~rollupfrontendfs#write",
    "class/src/jimpex/frontendFs.js~RollupFrontendFs.html#instance-method-write",
    "src/jimpex/frontendFs.js~RollupFrontendFs#write",
    "method"
  ],
  [
    "src/jimpex/index.js",
    "file/src/jimpex/index.js.html",
    "src/jimpex/index.js",
    "file"
  ],
  [
    "src/jimpex/sendfile.js",
    "file/src/jimpex/sendFile.js.html",
    "src/jimpex/sendFile.js",
    "file"
  ],
  [
    "src/jimpex/sendfile.js~rollupsendfile#constructor",
    "class/src/jimpex/sendFile.js~RollupSendFile.html#instance-constructor-constructor",
    "src/jimpex/sendFile.js~RollupSendFile#constructor",
    "method"
  ],
  [
    "src/jimpex/sendfile.js~rollupsendfile#frontendfs",
    "class/src/jimpex/sendFile.js~RollupSendFile.html#instance-member-frontendFs",
    "src/jimpex/sendFile.js~RollupSendFile#frontendFs",
    "member"
  ],
  [
    "src/jimpex/sendfile.js~rollupsendfile#sendfile",
    "class/src/jimpex/sendFile.js~RollupSendFile.html#instance-method-sendFile",
    "src/jimpex/sendFile.js~RollupSendFile#sendFile",
    "method"
  ],
  [
    "src/plugins/compression/index.js",
    "file/src/plugins/compression/index.js.html",
    "src/plugins/compression/index.js",
    "file"
  ],
  [
    "src/plugins/compression/index.js~projextrollupcompressionplugin#constructor",
    "class/src/plugins/compression/index.js~ProjextRollupCompressionPlugin.html#instance-constructor-constructor",
    "src/plugins/compression/index.js~ProjextRollupCompressionPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/compression/index.js~projextrollupcompressionplugin#filter",
    "class/src/plugins/compression/index.js~ProjextRollupCompressionPlugin.html#instance-member-filter",
    "src/plugins/compression/index.js~ProjextRollupCompressionPlugin#filter",
    "member"
  ],
  [
    "src/plugins/compression/index.js~projextrollupcompressionplugin#getoptions",
    "class/src/plugins/compression/index.js~ProjextRollupCompressionPlugin.html#instance-method-getOptions",
    "src/plugins/compression/index.js~ProjextRollupCompressionPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/compression/index.js~projextrollupcompressionplugin#name",
    "class/src/plugins/compression/index.js~ProjextRollupCompressionPlugin.html#instance-member-name",
    "src/plugins/compression/index.js~ProjextRollupCompressionPlugin#name",
    "member"
  ],
  [
    "src/plugins/compression/index.js~projextrollupcompressionplugin#onwrite",
    "class/src/plugins/compression/index.js~ProjextRollupCompressionPlugin.html#instance-method-onwrite",
    "src/plugins/compression/index.js~ProjextRollupCompressionPlugin#onwrite",
    "method"
  ],
  [
    "src/plugins/css/index.js",
    "file/src/plugins/css/index.js.html",
    "src/plugins/css/index.js",
    "file"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#constructor",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-constructor-constructor",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#filter",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-member-filter",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#filter",
    "member"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#getoptions",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-method-getOptions",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#intro",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-method-intro",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#intro",
    "method"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#name",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-member-name",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#name",
    "member"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#ongenerate",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-method-ongenerate",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#ongenerate",
    "method"
  ],
  [
    "src/plugins/css/index.js~projextrollupcssplugin#transform",
    "class/src/plugins/css/index.js~ProjextRollupCSSPlugin.html#instance-method-transform",
    "src/plugins/css/index.js~ProjextRollupCSSPlugin#transform",
    "method"
  ],
  [
    "src/plugins/css/insertfn.js",
    "file/src/plugins/css/insertFn.js.html",
    "src/plugins/css/insertFn.js",
    "file"
  ],
  [
    "src/plugins/devserver/index.js",
    "file/src/plugins/devServer/index.js.html",
    "src/plugins/devServer/index.js",
    "file"
  ],
  [
    "src/plugins/devserver/index.js~projextrollupdevserverplugin#constructor",
    "class/src/plugins/devServer/index.js~ProjextRollupDevServerPlugin.html#instance-constructor-constructor",
    "src/plugins/devServer/index.js~ProjextRollupDevServerPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/devserver/index.js~projextrollupdevserverplugin#getoptions",
    "class/src/plugins/devServer/index.js~ProjextRollupDevServerPlugin.html#instance-method-getOptions",
    "src/plugins/devServer/index.js~ProjextRollupDevServerPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/devserver/index.js~projextrollupdevserverplugin#name",
    "class/src/plugins/devServer/index.js~ProjextRollupDevServerPlugin.html#instance-member-name",
    "src/plugins/devServer/index.js~ProjextRollupDevServerPlugin#name",
    "member"
  ],
  [
    "src/plugins/devserver/index.js~projextrollupdevserverplugin#onwrite",
    "class/src/plugins/devServer/index.js~ProjextRollupDevServerPlugin.html#instance-method-onwrite",
    "src/plugins/devServer/index.js~ProjextRollupDevServerPlugin#onwrite",
    "method"
  ],
  [
    "src/plugins/devserver/index.js~projextrollupdevserverplugin#url",
    "class/src/plugins/devServer/index.js~ProjextRollupDevServerPlugin.html#instance-member-url",
    "src/plugins/devServer/index.js~ProjextRollupDevServerPlugin#url",
    "member"
  ],
  [
    "src/plugins/index.js",
    "file/src/plugins/index.js.html",
    "src/plugins/index.js",
    "file"
  ],
  [
    "src/plugins/noderunner/index.js",
    "file/src/plugins/nodeRunner/index.js.html",
    "src/plugins/nodeRunner/index.js",
    "file"
  ],
  [
    "src/plugins/noderunner/index.js~projextrollupnoderunnerplugin#constructor",
    "class/src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin.html#instance-constructor-constructor",
    "src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/noderunner/index.js~projextrollupnoderunnerplugin#getoptions",
    "class/src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin.html#instance-method-getOptions",
    "src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/noderunner/index.js~projextrollupnoderunnerplugin#name",
    "class/src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin.html#instance-member-name",
    "src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin#name",
    "member"
  ],
  [
    "src/plugins/noderunner/index.js~projextrollupnoderunnerplugin#onwrite",
    "class/src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin.html#instance-method-onwrite",
    "src/plugins/nodeRunner/index.js~ProjextRollupNodeRunnerPlugin#onwrite",
    "method"
  ],
  [
    "src/plugins/stats/index.js",
    "file/src/plugins/stats/index.js.html",
    "src/plugins/stats/index.js",
    "file"
  ],
  [
    "src/plugins/stats/index.js~projextrollupstatsplugin#add",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html#instance-method-add",
    "src/plugins/stats/index.js~ProjextRollupStatsPlugin#add",
    "method"
  ],
  [
    "src/plugins/stats/index.js~projextrollupstatsplugin#constructor",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html#instance-constructor-constructor",
    "src/plugins/stats/index.js~ProjextRollupStatsPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/stats/index.js~projextrollupstatsplugin#getoptions",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html#instance-method-getOptions",
    "src/plugins/stats/index.js~ProjextRollupStatsPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/stats/index.js~projextrollupstatsplugin#log",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html#instance-method-log",
    "src/plugins/stats/index.js~ProjextRollupStatsPlugin#log",
    "method"
  ],
  [
    "src/plugins/stats/index.js~projextrollupstatsplugin#name",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html#instance-member-name",
    "src/plugins/stats/index.js~ProjextRollupStatsPlugin#name",
    "member"
  ],
  [
    "src/plugins/stats/index.js~projextrollupstatsplugin#reset",
    "class/src/plugins/stats/index.js~ProjextRollupStatsPlugin.html#instance-method-reset",
    "src/plugins/stats/index.js~ProjextRollupStatsPlugin#reset",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/helper.js",
    "file/src/plugins/stylesheetAssets/helper.js.html",
    "src/plugins/stylesheetAssets/helper.js",
    "file"
  ],
  [
    "src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin#constructor",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html#instance-constructor-constructor",
    "src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin#filter",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html#instance-member-filter",
    "src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin#filter",
    "member"
  ],
  [
    "src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin#getoptions",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html#instance-method-getOptions",
    "src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin#intro",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html#instance-method-intro",
    "src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin#intro",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin#name",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html#instance-member-name",
    "src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin#name",
    "member"
  ],
  [
    "src/plugins/stylesheetassets/helper.js~projextrollupstylesheetassetshelperplugin#transform",
    "class/src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin.html#instance-method-transform",
    "src/plugins/stylesheetAssets/helper.js~ProjextRollupStylesheetAssetsHelperPlugin#transform",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/helperfn.js",
    "file/src/plugins/stylesheetAssets/helperFn.js.html",
    "src/plugins/stylesheetAssets/helperFn.js",
    "file"
  ],
  [
    "src/plugins/stylesheetassets/index.js",
    "file/src/plugins/stylesheetAssets/index.js.html",
    "src/plugins/stylesheetAssets/index.js",
    "file"
  ],
  [
    "src/plugins/stylesheetassets/index.js~projextrollupstylesheetassetsplugin#constructor",
    "class/src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.html#instance-constructor-constructor",
    "src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/index.js~projextrollupstylesheetassetsplugin#getoptions",
    "class/src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.html#instance-method-getOptions",
    "src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/index.js~projextrollupstylesheetassetsplugin#name",
    "class/src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.html#instance-member-name",
    "src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin#name",
    "member"
  ],
  [
    "src/plugins/stylesheetassets/index.js~projextrollupstylesheetassetsplugin#onwrite",
    "class/src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.html#instance-method-onwrite",
    "src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin#onwrite",
    "method"
  ],
  [
    "src/plugins/stylesheetassets/index.js~projextrollupstylesheetassetsplugin.helper",
    "class/src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.html#static-get-helper",
    "src/plugins/stylesheetAssets/index.js~ProjextRollupStylesheetAssetsPlugin.helper",
    "member"
  ],
  [
    "src/plugins/stylesheetmodulesfixer/index.js",
    "file/src/plugins/stylesheetModulesFixer/index.js.html",
    "src/plugins/stylesheetModulesFixer/index.js",
    "file"
  ],
  [
    "src/plugins/stylesheetmodulesfixer/index.js~projextrollupstylesheetmodulesfixerplugin#constructor",
    "class/src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin.html#instance-constructor-constructor",
    "src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/stylesheetmodulesfixer/index.js~projextrollupstylesheetmodulesfixerplugin#filter",
    "class/src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin.html#instance-member-filter",
    "src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin#filter",
    "member"
  ],
  [
    "src/plugins/stylesheetmodulesfixer/index.js~projextrollupstylesheetmodulesfixerplugin#getoptions",
    "class/src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin.html#instance-method-getOptions",
    "src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/stylesheetmodulesfixer/index.js~projextrollupstylesheetmodulesfixerplugin#name",
    "class/src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin.html#instance-member-name",
    "src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin#name",
    "member"
  ],
  [
    "src/plugins/stylesheetmodulesfixer/index.js~projextrollupstylesheetmodulesfixerplugin#transform",
    "class/src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin.html#instance-method-transform",
    "src/plugins/stylesheetModulesFixer/index.js~ProjextRollupStylesheetModulesFixerPlugin#transform",
    "method"
  ],
  [
    "src/plugins/template/index.js",
    "file/src/plugins/template/index.js.html",
    "src/plugins/template/index.js",
    "file"
  ],
  [
    "src/plugins/template/index.js~projextrolluptemplateplugin#constructor",
    "class/src/plugins/template/index.js~ProjextRollupTemplatePlugin.html#instance-constructor-constructor",
    "src/plugins/template/index.js~ProjextRollupTemplatePlugin#constructor",
    "method"
  ],
  [
    "src/plugins/template/index.js~projextrolluptemplateplugin#getoptions",
    "class/src/plugins/template/index.js~ProjextRollupTemplatePlugin.html#instance-method-getOptions",
    "src/plugins/template/index.js~ProjextRollupTemplatePlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/template/index.js~projextrolluptemplateplugin#name",
    "class/src/plugins/template/index.js~ProjextRollupTemplatePlugin.html#instance-member-name",
    "src/plugins/template/index.js~ProjextRollupTemplatePlugin#name",
    "member"
  ],
  [
    "src/plugins/template/index.js~projextrolluptemplateplugin#onwrite",
    "class/src/plugins/template/index.js~ProjextRollupTemplatePlugin.html#instance-method-onwrite",
    "src/plugins/template/index.js~ProjextRollupTemplatePlugin#onwrite",
    "method"
  ],
  [
    "src/plugins/urls/index.js",
    "file/src/plugins/urls/index.js.html",
    "src/plugins/urls/index.js",
    "file"
  ],
  [
    "src/plugins/urls/index.js~projextrollupurlsplugin#constructor",
    "class/src/plugins/urls/index.js~ProjextRollupURLsPlugin.html#instance-constructor-constructor",
    "src/plugins/urls/index.js~ProjextRollupURLsPlugin#constructor",
    "method"
  ],
  [
    "src/plugins/urls/index.js~projextrollupurlsplugin#getoptions",
    "class/src/plugins/urls/index.js~ProjextRollupURLsPlugin.html#instance-method-getOptions",
    "src/plugins/urls/index.js~ProjextRollupURLsPlugin#getOptions",
    "method"
  ],
  [
    "src/plugins/urls/index.js~projextrollupurlsplugin#load",
    "class/src/plugins/urls/index.js~ProjextRollupURLsPlugin.html#instance-method-load",
    "src/plugins/urls/index.js~ProjextRollupURLsPlugin#load",
    "method"
  ],
  [
    "src/plugins/urls/index.js~projextrollupurlsplugin#name",
    "class/src/plugins/urls/index.js~ProjextRollupURLsPlugin.html#instance-member-name",
    "src/plugins/urls/index.js~ProjextRollupURLsPlugin#name",
    "member"
  ],
  [
    "src/plugins/urls/index.js~projextrollupurlsplugin#onwrite",
    "class/src/plugins/urls/index.js~ProjextRollupURLsPlugin.html#instance-method-onwrite",
    "src/plugins/urls/index.js~ProjextRollupURLsPlugin#onwrite",
    "method"
  ],
  [
    "src/plugins/utils.js",
    "file/src/plugins/utils.js.html",
    "src/plugins/utils.js",
    "file"
  ],
  [
    "src/plugins/utils.js~projextrolluputils.createlogger",
    "class/src/plugins/utils.js~ProjextRollupUtils.html#static-method-createLogger",
    "src/plugins/utils.js~ProjextRollupUtils.createLogger",
    "method"
  ],
  [
    "src/plugins/utils.js~projextrolluputils.escaperegex",
    "class/src/plugins/utils.js~ProjextRollupUtils.html#static-method-escapeRegex",
    "src/plugins/utils.js~ProjextRollupUtils.escapeRegex",
    "method"
  ],
  [
    "src/plugins/utils.js~projextrolluputils.formatplaceholder",
    "class/src/plugins/utils.js~ProjextRollupUtils.html#static-method-formatPlaceholder",
    "src/plugins/utils.js~ProjextRollupUtils.formatPlaceholder",
    "method"
  ],
  [
    "src/plugins/windowasglobal/index.js",
    "file/src/plugins/windowAsGlobal/index.js.html",
    "src/plugins/windowAsGlobal/index.js",
    "file"
  ],
  [
    "src/plugins/windowasglobal/index.js~projextrollupwindowasglobalplugin#intro",
    "class/src/plugins/windowAsGlobal/index.js~ProjextRollupWindowAsGlobalPlugin.html#instance-method-intro",
    "src/plugins/windowAsGlobal/index.js~ProjextRollupWindowAsGlobalPlugin#intro",
    "method"
  ],
  [
    "src/services/building/configuration.js",
    "file/src/services/building/configuration.js.html",
    "src/services/building/configuration.js",
    "file"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#buildversion",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-member-buildVersion",
    "src/services/building/configuration.js~RollupConfiguration#buildVersion",
    "member"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#constructor",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-constructor-constructor",
    "src/services/building/configuration.js~RollupConfiguration#constructor",
    "method"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#getconfig",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-method-getConfig",
    "src/services/building/configuration.js~RollupConfiguration#getConfig",
    "method"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#rollupconfigurations",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-member-rollupConfigurations",
    "src/services/building/configuration.js~RollupConfiguration#rollupConfigurations",
    "member"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#targetconfiguration",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-member-targetConfiguration",
    "src/services/building/configuration.js~RollupConfiguration#targetConfiguration",
    "member"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#targets",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-member-targets",
    "src/services/building/configuration.js~RollupConfiguration#targets",
    "member"
  ],
  [
    "src/services/building/configuration.js~rollupconfiguration#targetsfilerules",
    "class/src/services/building/configuration.js~RollupConfiguration.html#instance-member-targetsFileRules",
    "src/services/building/configuration.js~RollupConfiguration#targetsFileRules",
    "member"
  ],
  [
    "src/services/building/engine.js",
    "file/src/services/building/engine.js.html",
    "src/services/building/engine.js",
    "file"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#constructor",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-constructor-constructor",
    "src/services/building/engine.js~RollupBuildEngine#constructor",
    "method"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#environmentutils",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-member-environmentUtils",
    "src/services/building/engine.js~RollupBuildEngine#environmentUtils",
    "member"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#getbuildcommand",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-method-getBuildCommand",
    "src/services/building/engine.js~RollupBuildEngine#getBuildCommand",
    "method"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#getconfiguration",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-method-getConfiguration",
    "src/services/building/engine.js~RollupBuildEngine#getConfiguration",
    "method"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#getrollupconfig",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-method-getRollupConfig",
    "src/services/building/engine.js~RollupBuildEngine#getRollupConfig",
    "method"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#rollupconfiguration",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-member-rollupConfiguration",
    "src/services/building/engine.js~RollupBuildEngine#rollupConfiguration",
    "member"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#rollupplugininfo",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-member-rollupPluginInfo",
    "src/services/building/engine.js~RollupBuildEngine#rollupPluginInfo",
    "member"
  ],
  [
    "src/services/building/engine.js~rollupbuildengine#targets",
    "class/src/services/building/engine.js~RollupBuildEngine.html#instance-member-targets",
    "src/services/building/engine.js~RollupBuildEngine#targets",
    "member"
  ],
  [
    "src/services/building/index.js",
    "file/src/services/building/index.js.html",
    "src/services/building/index.js",
    "file"
  ],
  [
    "src/services/configurations/browserdevelopmentconfiguration.js",
    "file/src/services/configurations/browserDevelopmentConfiguration.js.html",
    "src/services/configurations/browserDevelopmentConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/browserdevelopmentconfiguration.js~rollupbrowserdevelopmentconfiguration#constructor",
    "class/src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/browserdevelopmentconfiguration.js~rollupbrowserdevelopmentconfiguration#createconfig",
    "class/src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration.html#instance-method-createConfig",
    "src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration#createConfig",
    "method"
  ],
  [
    "src/services/configurations/browserdevelopmentconfiguration.js~rollupbrowserdevelopmentconfiguration#events",
    "class/src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration.html#instance-member-events",
    "src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration#events",
    "member"
  ],
  [
    "src/services/configurations/browserdevelopmentconfiguration.js~rollupbrowserdevelopmentconfiguration#rolluppluginsettingsconfiguration",
    "class/src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration.html#instance-member-rollupPluginSettingsConfiguration",
    "src/services/configurations/browserDevelopmentConfiguration.js~RollupBrowserDevelopmentConfiguration#rollupPluginSettingsConfiguration",
    "member"
  ],
  [
    "src/services/configurations/browserproductionconfiguration.js",
    "file/src/services/configurations/browserProductionConfiguration.js.html",
    "src/services/configurations/browserProductionConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/browserproductionconfiguration.js~rollupbrowserproductionconfiguration#constructor",
    "class/src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/browserproductionconfiguration.js~rollupbrowserproductionconfiguration#createconfig",
    "class/src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration.html#instance-method-createConfig",
    "src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration#createConfig",
    "method"
  ],
  [
    "src/services/configurations/browserproductionconfiguration.js~rollupbrowserproductionconfiguration#events",
    "class/src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration.html#instance-member-events",
    "src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration#events",
    "member"
  ],
  [
    "src/services/configurations/browserproductionconfiguration.js~rollupbrowserproductionconfiguration#rolluppluginsettingsconfiguration",
    "class/src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration.html#instance-member-rollupPluginSettingsConfiguration",
    "src/services/configurations/browserProductionConfiguration.js~RollupBrowserProductionConfiguration#rollupPluginSettingsConfiguration",
    "member"
  ],
  [
    "src/services/configurations/index.js",
    "file/src/services/configurations/index.js.html",
    "src/services/configurations/index.js",
    "file"
  ],
  [
    "src/services/configurations/nodedevelopmentconfiguration.js",
    "file/src/services/configurations/nodeDevelopmentConfiguration.js.html",
    "src/services/configurations/nodeDevelopmentConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/nodedevelopmentconfiguration.js~rollupnodedevelopmentconfiguration#constructor",
    "class/src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/nodedevelopmentconfiguration.js~rollupnodedevelopmentconfiguration#createconfig",
    "class/src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration.html#instance-method-createConfig",
    "src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration#createConfig",
    "method"
  ],
  [
    "src/services/configurations/nodedevelopmentconfiguration.js~rollupnodedevelopmentconfiguration#events",
    "class/src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration.html#instance-member-events",
    "src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration#events",
    "member"
  ],
  [
    "src/services/configurations/nodedevelopmentconfiguration.js~rollupnodedevelopmentconfiguration#rolluppluginsettingsconfiguration",
    "class/src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration.html#instance-member-rollupPluginSettingsConfiguration",
    "src/services/configurations/nodeDevelopmentConfiguration.js~RollupNodeDevelopmentConfiguration#rollupPluginSettingsConfiguration",
    "member"
  ],
  [
    "src/services/configurations/nodeproductionconfiguration.js",
    "file/src/services/configurations/nodeProductionConfiguration.js.html",
    "src/services/configurations/nodeProductionConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/nodeproductionconfiguration.js~rollupnodeproductionconfiguration#constructor",
    "class/src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/nodeproductionconfiguration.js~rollupnodeproductionconfiguration#createconfig",
    "class/src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration.html#instance-method-createConfig",
    "src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration#createConfig",
    "method"
  ],
  [
    "src/services/configurations/nodeproductionconfiguration.js~rollupnodeproductionconfiguration#events",
    "class/src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration.html#instance-member-events",
    "src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration#events",
    "member"
  ],
  [
    "src/services/configurations/nodeproductionconfiguration.js~rollupnodeproductionconfiguration#rolluppluginsettingsconfiguration",
    "class/src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration.html#instance-member-rollupPluginSettingsConfiguration",
    "src/services/configurations/nodeProductionConfiguration.js~RollupNodeProductionConfiguration#rollupPluginSettingsConfiguration",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js",
    "file/src/services/configurations/pluginsConfiguration.js.html",
    "src/services/configurations/pluginsConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#applogger",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-appLogger",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#appLogger",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#babelconfiguration",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-babelConfiguration",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#babelConfiguration",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#babelhelper",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-babelHelper",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#babelHelper",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#constructor",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#createconfig",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-method-createConfig",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#createConfig",
    "method"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#events",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-events",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#events",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#packageinfo",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-packageInfo",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#packageInfo",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#rollupplugininfo",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-rollupPluginInfo",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#rollupPluginInfo",
    "member"
  ],
  [
    "src/services/configurations/pluginsconfiguration.js~rolluppluginsettingsconfiguration#targetshtml",
    "class/src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration.html#instance-member-targetsHTML",
    "src/services/configurations/pluginsConfiguration.js~RollupPluginSettingsConfiguration#targetsHTML",
    "member"
  ],
  [
    "src/services/server/index.js",
    "file/src/services/server/index.js.html",
    "src/services/server/index.js",
    "file"
  ],
  [
    "src/services/server/middleware.js",
    "file/src/services/server/middleware.js.html",
    "src/services/server/middleware.js",
    "file"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#_watcher",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-member-_watcher",
    "src/services/server/middleware.js~RollupMiddleware#_watcher",
    "member"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#applogger",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-member-appLogger",
    "src/services/server/middleware.js~RollupMiddleware#appLogger",
    "member"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#constructor",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-constructor-constructor",
    "src/services/server/middleware.js~RollupMiddleware#constructor",
    "method"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#events",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-member-events",
    "src/services/server/middleware.js~RollupMiddleware#events",
    "member"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#generate",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-method-generate",
    "src/services/server/middleware.js~RollupMiddleware#generate",
    "method"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#rollupconfiguration",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-member-rollupConfiguration",
    "src/services/server/middleware.js~RollupMiddleware#rollupConfiguration",
    "member"
  ],
  [
    "src/services/server/middleware.js~rollupmiddleware#targets",
    "class/src/services/server/middleware.js~RollupMiddleware.html#instance-member-targets",
    "src/services/server/middleware.js~RollupMiddleware#targets",
    "member"
  ],
  [
    "src/typedef.js",
    "file/src/typedef.js.html",
    "src/typedef.js",
    "file"
  ],
  [
    "src/typedef.js~babelconfiguration",
    "ttps://homer0.github.io/projext/class/src/services/configurations/babelConfiguration.js~BabelConfiguration.html",
    "src/typedef.js~BabelConfiguration",
    "external"
  ],
  [
    "src/typedef.js~buildversion",
    "https://homer0.github.io/projext/class/src/services/building/buildVersion.js~BuildVersion.html",
    "src/typedef.js~BuildVersion",
    "external"
  ],
  [
    "src/typedef.js~environmentutils",
    "https://homer0.github.io/wootils/class/wootils/node/environmentUtils.js~EnvironmentUtils.html",
    "src/typedef.js~EnvironmentUtils",
    "external"
  ],
  [
    "src/typedef.js~events",
    "https://homer0.github.io/projext/class/src/services/common/events.js~Events.html",
    "src/typedef.js~Events",
    "external"
  ],
  [
    "src/typedef.js~express",
    "https://expressjs.com",
    "src/typedef.js~Express",
    "external"
  ],
  [
    "src/typedef.js~filesystem",
    "https://nodejs.org/api/fs.html",
    "src/typedef.js~FileSystem",
    "external"
  ],
  [
    "src/typedef.js~httprequest",
    "https://nodejs.org/api/http.html#http_class_http_clientrequest",
    "src/typedef.js~HTTPRequest",
    "external"
  ],
  [
    "src/typedef.js~httpresponse",
    "https://nodejs.org/api/http.html#http_class_http_serverresponse",
    "src/typedef.js~HTTPResponse",
    "external"
  ],
  [
    "src/typedef.js~jimpex",
    "https://yarnpkg.com/en/package/jimpex",
    "src/typedef.js~Jimpex",
    "external"
  ],
  [
    "src/typedef.js~jimple",
    "https://yarnpkg.com/en/package/jimple",
    "src/typedef.js~Jimple",
    "external"
  ],
  [
    "src/typedef.js~logger",
    "https://homer0.github.io/wootils/class/wootils/node/logger.js~Logger.html",
    "src/typedef.js~Logger",
    "external"
  ],
  [
    "src/typedef.js~middleware",
    "http://expressjs.com/en/guide/using-middleware.html",
    "src/typedef.js~Middleware",
    "external"
  ],
  [
    "src/typedef.js~middlewaregetdirectory",
    "typedef/index.html#static-typedef-MiddlewareGetDirectory",
    "src/typedef.js~MiddlewareGetDirectory",
    "typedef"
  ],
  [
    "src/typedef.js~middlewaregetfilesystem",
    "typedef/index.html#static-typedef-MiddlewareGetFileSystem",
    "src/typedef.js~MiddlewareGetFileSystem",
    "typedef"
  ],
  [
    "src/typedef.js~middlewareinformation",
    "typedef/index.html#static-typedef-MiddlewareInformation",
    "src/typedef.js~MiddlewareInformation",
    "typedef"
  ],
  [
    "src/typedef.js~pathutils",
    "https://homer0.github.io/wootils/class/wootils/node/pathUtils.js~PathUtils.html",
    "src/typedef.js~PathUtils",
    "external"
  ],
  [
    "src/typedef.js~projext",
    "https://homer0.github.io/projext/class/src/app/index.js~Projext.html",
    "src/typedef.js~Projext",
    "external"
  ],
  [
    "src/typedef.js~projextrollupcsspluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupCSSPluginOptions",
    "src/typedef.js~ProjextRollupCSSPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupcompressionpluginentry",
    "typedef/index.html#static-typedef-ProjextRollupCompressionPluginEntry",
    "src/typedef.js~ProjextRollupCompressionPluginEntry",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupcompressionpluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupCompressionPluginOptions",
    "src/typedef.js~ProjextRollupCompressionPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupdevserverpluginevent",
    "typedef/index.html#static-typedef-ProjextRollupDevServerPluginEvent",
    "src/typedef.js~ProjextRollupDevServerPluginEvent",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupdevserverpluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupDevServerPluginOptions",
    "src/typedef.js~ProjextRollupDevServerPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupnoderunnerpluginevent",
    "typedef/index.html#static-typedef-ProjextRollupNodeRunnerPluginEvent",
    "src/typedef.js~ProjextRollupNodeRunnerPluginEvent",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupnoderunnerpluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupNodeRunnerPluginOptions",
    "src/typedef.js~ProjextRollupNodeRunnerPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrolluppluginurl",
    "typedef/index.html#static-typedef-ProjextRollupPluginURL",
    "src/typedef.js~ProjextRollupPluginURL",
    "typedef"
  ],
  [
    "src/typedef.js~projextrolluppluginsstats",
    "typedef/index.html#static-typedef-ProjextRollupPluginsStats",
    "src/typedef.js~ProjextRollupPluginsStats",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstatsplugincellswidth",
    "typedef/index.html#static-typedef-ProjextRollupStatsPluginCellsWidth",
    "src/typedef.js~ProjextRollupStatsPluginCellsWidth",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstatspluginlog",
    "typedef/index.html#static-typedef-ProjextRollupStatsPluginLog",
    "src/typedef.js~ProjextRollupStatsPluginLog",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstatspluginlogoptions",
    "typedef/index.html#static-typedef-ProjextRollupStatsPluginLogOptions",
    "src/typedef.js~ProjextRollupStatsPluginLogOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstatspluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupStatsPluginOptions",
    "src/typedef.js~ProjextRollupStatsPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstatspluginreset",
    "typedef/index.html#static-typedef-ProjextRollupStatsPluginReset",
    "src/typedef.js~ProjextRollupStatsPluginReset",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstylesheetassetshelperpluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupStylesheetAssetsHelperPluginOptions",
    "src/typedef.js~ProjextRollupStylesheetAssetsHelperPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstylesheetassetspluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupStylesheetAssetsPluginOptions",
    "src/typedef.js~ProjextRollupStylesheetAssetsPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupstylesheetmodulesfixerpluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupStylesheetModulesFixerPluginOptions",
    "src/typedef.js~ProjextRollupStylesheetModulesFixerPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrolluptemplatepluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupTemplatePluginOptions",
    "src/typedef.js~ProjextRollupTemplatePluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projextrollupurlspluginoptions",
    "typedef/index.html#static-typedef-ProjextRollupURLsPluginOptions",
    "src/typedef.js~ProjextRollupURLsPluginOptions",
    "typedef"
  ],
  [
    "src/typedef.js~provider",
    "typedef/index.html#static-typedef-Provider",
    "src/typedef.js~Provider",
    "typedef"
  ],
  [
    "src/typedef.js~providerregistermethod",
    "typedef/index.html#static-typedef-ProviderRegisterMethod",
    "src/typedef.js~ProviderRegisterMethod",
    "typedef"
  ],
  [
    "src/typedef.js~rollupconfigurationoutputparams",
    "typedef/index.html#static-typedef-RollupConfigurationOutputParams",
    "src/typedef.js~RollupConfigurationOutputParams",
    "typedef"
  ],
  [
    "src/typedef.js~rollupconfigurationpathsparams",
    "typedef/index.html#static-typedef-RollupConfigurationPathsParams",
    "src/typedef.js~RollupConfigurationPathsParams",
    "typedef"
  ],
  [
    "src/typedef.js~rollupconfigurations",
    "typedef/index.html#static-typedef-RollupConfigurations",
    "src/typedef.js~RollupConfigurations",
    "typedef"
  ],
  [
    "src/typedef.js~rollupconfigurationsbyenvironment",
    "typedef/index.html#static-typedef-RollupConfigurationsByEnvironment",
    "src/typedef.js~RollupConfigurationsByEnvironment",
    "typedef"
  ],
  [
    "src/typedef.js~rollupfiledefinition",
    "typedef/index.html#static-typedef-RollupFileDefinition",
    "src/typedef.js~RollupFileDefinition",
    "typedef"
  ],
  [
    "src/typedef.js~rollupfilter",
    "typedef/index.html#static-typedef-RollupFilter",
    "src/typedef.js~RollupFilter",
    "typedef"
  ],
  [
    "src/typedef.js~rollupplugininfo",
    "typedef/index.html#static-typedef-RollupPluginInfo",
    "src/typedef.js~RollupPluginInfo",
    "typedef"
  ],
  [
    "src/typedef.js~rollupstylesheetprocessor",
    "typedef/index.html#static-typedef-RollupStylesheetProcessor",
    "src/typedef.js~RollupStylesheetProcessor",
    "typedef"
  ],
  [
    "src/typedef.js~stringorobject",
    "typedef/index.html#static-typedef-StringOrObject",
    "src/typedef.js~StringOrObject",
    "typedef"
  ],
  [
    "src/typedef.js~target",
    "https://homer0.github.io/projext/typedef/index.html#static-typedef-Target",
    "src/typedef.js~Target",
    "external"
  ],
  [
    "src/typedef.js~targetconfigurationcreator",
    "https://homer0.github.io/projext/typedef/index.html#static-typedef-TargetConfigurationCreator",
    "src/typedef.js~TargetConfigurationCreator",
    "external"
  ],
  [
    "src/typedef.js~targetfilerules",
    "https://homer0.github.io/projext/typedef/index.html#static-typedef-TargetFileRules",
    "src/typedef.js~TargetFileRules",
    "external"
  ],
  [
    "src/typedef.js~targets",
    "https://homer0.github.io/projext/class/src/services/targets/targets.js~Targets.html",
    "src/typedef.js~Targets",
    "external"
  ],
  [
    "src/typedef.js~targetsfilerules",
    "ttps://homer0.github.io/projext/class/src/services/targets/targetsFileRules/targetsFileRules.js~TargetsFileRules.html",
    "src/typedef.js~TargetsFileRules",
    "external"
  ],
  [
    "src/typedef.js~targetshtml",
    "https://homer0.github.io/projext/class/src/services/targets/targetsHTML.js~TargetsHTML.html",
    "src/typedef.js~TargetsHTML",
    "external"
  ]
]